# Generated by Django 4.2.2 on 2024-01-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_page_heading_4_page_list_item_description_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='list_item_description_5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='list_item_description_6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='list_item_description_7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='list_item_description_8',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='list_item_heading_5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='list_item_heading_6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='list_item_heading_7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='list_item_heading_8',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='text_4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='text_1',
            field=models.TextField(max_length=210),
        ),
    ]
