# Generated by Django 5.0.2 on 2024-03-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_page_text_5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=50)),
                ('images', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.AlterField(
            model_name='page',
            name='heading_5',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
