# Generated by Django 5.0.2 on 2024-03-13 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_gallery_alter_page_heading_5'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Photo',
        ),
    ]
