# Generated by Django 5.0.2 on 2024-03-14 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_rename_gallery_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.CreateModel(
            name='FacilityPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/')),
                ('photo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.photo')),
            ],
        ),
    ]
