# Generated by Django 5.0.2 on 2024-03-14 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_photo_images_facilityphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='images',
        ),
    ]
