# Generated by Django 5.0.2 on 2024-03-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_facilityphoto_name_alter_facilityphoto_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityphoto',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
