# Generated by Django 5.0.2 on 2024-03-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_facilityphoto_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityphoto',
            name='facility',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
