# Generated by Django 5.0.2 on 2024-03-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_facilityphoto_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityphoto',
            name='facility',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
