# Generated by Django 5.0.2 on 2024-03-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_alter_facilityphoto_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityphoto',
            name='facility',
            field=models.CharField(blank=True, default='Photo.facility', max_length=50),
        ),
    ]
