# Generated by Django 5.0.2 on 2024-03-18 08:10

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_alter_facilityphoto_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityphoto',
            name='facility',
            field=models.CharField(blank=True, default=website.models.Photo, max_length=50),
        ),
    ]
