# Generated by Django 5.0.2 on 2024-03-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_remove_facilityphoto_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='email',
            field=models.CharField(default=models.CharField(max_length=50), max_length=50),
        ),
    ]
