# Generated by Django 5.0.2 on 2024-03-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_alter_facilityphoto_photo_alter_photo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='images',
            field=models.ImageField(default='fs', upload_to=''),
            preserve_default=False,
        ),
    ]
