# Generated by Django 5.0.2 on 2024-03-18 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_remove_photo_email_remove_photo_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilityphoto',
            options={'verbose_name': 'Zdjecia placowki'},
        ),
    ]
