# Generated by Django 5.0.2 on 2024-03-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_alter_facilityphoto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilityphoto',
            options={},
        ),
    ]
