# Generated by Django 5.0.2 on 2024-03-18 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_alter_facilityphoto_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilityphoto',
            old_name='images',
            new_name='image',
        ),
    ]
