# Generated by Django 4.2.2 on 2024-01-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_basicdata_nurserydetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='heading_4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='page',
            name='list_item_description_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='list_item_description_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='list_item_description_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='list_item_description_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='list_item_heading_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='list_item_heading_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='list_item_heading_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='list_item_heading_4',
            field=models.TextField(blank=True),
        ),
    ]
