# Generated by Django 4.2.2 on 2024-01-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_page_list_item_description_5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='heading_5',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
