# Generated by Django 4.2.2 on 2024-02-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_page_heading_5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
