# Generated by Django 4.2.2 on 2024-02-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_page_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=50)),
                ('list_item_heading_1', models.TextField(blank=True)),
                ('list_item_description_1', models.TextField(blank=True)),
                ('list_item_heading_2', models.TextField(blank=True)),
                ('list_item_description_2', models.TextField(blank=True)),
                ('list_item_heading_3', models.TextField(blank=True)),
                ('list_item_description_3', models.TextField(blank=True)),
                ('list_item_heading_4', models.TextField(blank=True)),
                ('list_item_description_4', models.TextField(blank=True)),
                ('list_item_heading_5', models.TextField(blank=True)),
                ('list_item_description_5', models.TextField(blank=True)),
                ('list_item_heading_6', models.TextField(blank=True)),
                ('list_item_description_6', models.TextField(blank=True)),
                ('list_item_heading_7', models.TextField(blank=True)),
                ('list_item_description_7', models.TextField(blank=True)),
                ('list_item_heading_8', models.TextField(blank=True)),
                ('list_item_description_8', models.TextField(blank=True)),
                ('list_item_heading_9', models.TextField(blank=True)),
                ('list_item_description_9', models.TextField(blank=True)),
                ('list_item_heading_10', models.TextField(blank=True)),
                ('list_item_description_10', models.TextField(blank=True)),
                ('list_item_heading_11', models.TextField(blank=True)),
                ('list_item_description_11', models.TextField(blank=True)),
                ('list_item_heading_12', models.TextField(blank=True)),
                ('list_item_description_12', models.TextField(blank=True)),
                ('list_item_heading_13', models.TextField(blank=True)),
                ('list_item_description_13', models.TextField(blank=True)),
                ('list_item_heading_14', models.TextField(blank=True)),
                ('list_item_description_14', models.TextField(blank=True)),
                ('list_item_heading_15', models.TextField(blank=True)),
                ('list_item_description_15', models.TextField(blank=True)),
            ],
        ),
    ]
